require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/LineLength:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
