name: RSpec
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  tests:
    name: Run RSpec tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7']
        # ruby-version: ['2.6', '2.7', '3.0', '3.1', 'head']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Bundle
        run: bundle install
      - name: RSpec
        run: bundle exec rspec
